# Generated by Django 5.0.4 on 2024-04-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='TodoModel',
        ),
    ]
